abstract final class AppRoutes {
  static const splash = '/';
  static const shell = '/shell';
  static const daily = '/daily';
  static const home = '/home';
  static const plans = '/plans';
  static const history = '/history';
  static const dashboard = '/dashboard';
  static const catProfile = '/cat-profile';
  static const catGroup = '/cat-group';
  static const groupFeedingDashboard = '/group-feeding-dashboard';
  static const settings = '/settings';
  static const notifications = '/notifications';
  static const howItWorks = '/how-it-works';
  static const scanner = '/scanner';
  static const weightCheckIn = '/weight-check-in';
  static const foodDatabase = '/food-database';
  static const weeklyDietReport = '/weekly-diet-report';
}
